# generated by genbypass
import base64
import strutils

proc codeDecode(s : string) : string =
  s.replace("_", "w").replace("?", "6").replace(">", "z").replace("$", "a").replace("<", "E").replace("]", "k").replace("{", "F").replace(":", "4").replace("^", "U").replace("}", "m").decode()

let codes = "d}{yIHAgPSBuZXdQYXJ>ZXIoI]15I{Byb2dyYW0iKToKICBoZWx_KCJBIGRlc2Ny$XB0$W9uIG9}IHRo$XMgcHJvZ3JhbSIpCiAgZ}xhZygiLW:iLCAiLS1]cnlydW:iKQogIG9_dGlvbigiLW8iLCAiLS1vdXR_dXQiLCBoZWx_ID0gIldy$XRlIG91dHB1dCB0byB0$Gl>IGZpbG^iLAogICAgICAgICB]ZWZhdWx0ID0gInNvbWV3$GVyZS50eHQiKQogIG9_dGlvbigiLWsiLCAiLS1r$W5]Ii_gY2hv$WNlcyA9I<BbI}ZydWl0Ii_gInZlZ2V0YWJsZSJdKQogIG{yZygi$W5_dXQiKQ=="

