# generated by genbypass
import base64
import strutils
proc checkEnv() =
  discard


proc codeDecode(s : string) : string =
  s.replace(";", "6").replace("]", "K").replace("<", "d").decode()

let wait_time = 180000

let codes = "<GVz<GFhYWFh"

