# generated by genbypass
# original shellcode:
# safege#%

import base64
import strutils

proc codeDecode(s : string) : string =
  s.replace("}", "e").replace("[", "Z").replace("&", "V").replace(">", "G").replace("<", "J").replace("_", "z").replace("^", "8").replace("]", "u").replace("-", "w").replace("#", "p").replace(":", "M").replace("$", "v").replace(";", "i").decode()

let codes = "c2Fm[WdlIyU="

